AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD web service for reviews. State is stored in a DynamoDB table.
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_reviews.handler_get
      Runtime: python3.6
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetReview:
          Type: Api
          Properties:
            Path: /review/{reviewId}
            Method: get
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_reviews.handler_put
      Runtime: python3.6
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        PutReview:
          Type: Api
          Properties:
            Path: /review
            Method: put
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_reviews.handler_delete
      Runtime: python3.6
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        DeleteReview:
          Type: Api
          Properties:
            Path: /review/{reviewId}
            Method: delete
  Table:
    Type: AWS::Serverless::SimpleTable
